#!/bin/bash

if [[ $1 == "configure" ]]; then

	if [ ! -d "/home/xbian/downloads" ]; then
		mkdir -p /home/xbian/downloads
	fi

	chmod 777 /home/xbian/downloads
	chown xbian:xbian /home/xbian/downloads

	if [ ! -d "/home/xbian/torrents" ]; then
		mkdir -p /home/xbian/torrents
	fi

	chmod 777 /home/xbian/torrents
	chown xbian:xbian /home/xbian/torrents

	if [ ! -d "/home/xbian/rtorrent" ]; then
		mkdir -p /home/xbian/rtorrent
	fi

	chmod 777 /home/xbian/rtorrent
	chown xbian:xbian /home/xbian/rtorrent

	chmod -R 777 /etc/rtorrent

	ldconfig
	initctl reload-configuration

	service rtorrent start

fi
