#!/bin/bash

if [[ $1 == "configure" ]]; then

	if [ ! -d "/home/xbian/downloads" ]; then
		mkdir -p /home/xbian/downloads
	fi

	chmod 777 /home/xbian/downloads
	chown xbian:xbian /home/xbian/downloads

	if [ ! -d "/home/xbian/torrents" ]; then
		mkdir -p /home/xbian/torrents
	fi

	chmod 777 /home/xbian/torrents
	chown xbian:xbian /home/xbian/torrents

	if [ ! -d "/home/xbian/rtorrent" ]; then
		mkdir -p /home/xbian/rtorrent
	fi

	chmod 777 /home/xbian/rtorrent
	chown xbian:xbian /home/xbian/rtorrent

	chmod -R 777 /etc/rtorrent

	ldconfig
	initctl reload-configuration

	useradd -G www-data xbian

	chown -R xbian:www-data /var/www/rutorrent
	chmod -R 770 /var/www/rutorrent

	ln -s /etc/nginx/sites-available/rutorrent /etc/nginx/sites-enabled/rutorrent

	sed -i 's/;env\[PATH\]/env\[PATH\]/g' /etc/php5/fpm/pool.d/www.conf

	service php5-fpm restart
	service nginx restart
	service rtorrent start

fi
